# Generated by Django 5.1 on 2024-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_like_or_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email_news',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_news',
        ),
        migrations.AddField(
            model_name='post',
            name='news_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='write a contact email address'),
        ),
        migrations.AddField(
            model_name='post',
            name='news_url',
            field=models.URLField(null=True, verbose_name='write the url of news origin'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True, verbose_name='write the text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/', verbose_name='download picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_or_dislike',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Enter a title'),
        ),
    ]
